name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: "Install NPM dependencies"
      run: |
        # Workaround (see https://github.com/gridsome/gridsome/issues/1385)
        export VUE_CLI_BABEL_TRANSPILE_MODULES=true
        npm install

    - name: "Build"
      run: |
        # Workaround (see https://github.com/gridsome/gridsome/issues/1385)
        export VUE_CLI_BABEL_TRANSPILE_MODULES=true
        npm run deploy

    - name: "Deploy"
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
        publish_branch: master
        external_repository: Ryujinx/ryujinx.github.io 
        user_name: GitHub Action
        user_email: action@github.com
        force_orphan: true
